corca-ai/adcio.js

- src/adcio/adcio.interface.ts
- src/adcio/adcio.ts
- src/lib/core/core.interface.ts
- src/lib/core/core.ts
Fix
NONE
- customerId 가 required 입니다.
- customerId를 옵셔널로 바꿉니다.
> NONE) fix: optional customerId

- package.json
- src/api/controller/v1/.openapi-generator/FILES
- src/api/controller/v1/api.ts
Build
NONE
- 0.1.0 배포를 위한 준비가 필요합니다.
- packages.json에서 버전을 0.1.0 로 올렸습니다.
- gen-api를 다시 돌렸습니다.
> NONE) build: ready v0.1.0

- package.json
- src/api/receiver/v1/api.ts
- src/lib/analytics/analytics.interface.ts
- src/lib/analytics/analytics.ts
Fix
ADCIO-1548
- click / impression 콜에서 session dto를 포함하지 않습니다.
- 포함하도록 수정했습니다.
> ADCIO-1548) fix: include session dto on click or impression

- package.json
- yarn.lock
Build
None
- 불필요하게 @openapitools/openapi-generator-cli 를 dependency로 가지고 있습니다.
- 위 패키지 내의 axios 버전에서 취약점이 발견되었습니다: https://github.com/corca-ai/adcio.js/security/dependabot/1
- @openapitools/openapi-generator-cli 를 삭제하고 axios 를 명시적으로 추가합니다.
> build: add axios and remove @openapitools/openapi-generator-cli

- package.json
- src/adcio/adcio.interface.ts
- src/adcio/adcio.ts
- src/lib/analytics/analytics.interface.ts
- src/lib/placement/placement.interface.ts
- tsconfig.json
- yarn.lock
Build
None
- 컴파일 시 paths 반영이 되지 않아 절대 경로로 import한 파일들이 import path를 못찾습니다.
- 추가로 src/lib 내부 파일들에서 src/adcio 내부 파일을 import 합니다. circular import 우려가 있습니다.
- tscpaths 이용해서 해결했습니다.
- src/adcio 내부 파일들은 다른 곳에서 import 하지 않도록 리팩토링했습니다.
> build: add tscpaths and refactor things

- package.json
- src/adcio/adcio.interface.ts
- src/adcio/adcio.ts
Fix
- onImpression 함수가 빠져있었습니다.
- 추가했습니다.
> fix: add on impression

- package.json
- src/lib/storage/session.storage.ts
ADCIO-
SessionStorage constructor에 expiration 타이머를 넣어주지 않았습니다.
SessionStorage constructor에 expiration 하는 타이머를 추가하였습니다.
> NONE) fix: Add expiration timer to SessionStorage

- package.json
- src/__tests__/adcio.spec.ts
- src/__tests__/setup.ts
- src/lib/storage/session.storage.ts
- yarn.lock
ADCIO-1753
Adcio.js SDK에 대한 테스트코드가 존재하지 않았습니다.
테크스펙에서 언급했던대로, mockup server가 필요없는 테스트코드 먼저 리뷰 요청을 드립니다.
1. testEnvironment를 jsdom으로 변경
- 이유: window 속성들을 이용하기 위함
2. crypto를 mockup함
- 이유: window.crypto가 jsdom에 정의되어 있지 않아, 사용할 수 없었기 때문
- 참고 링크: https://github.com/jsdom/jsdom/issues/1612
-> adcio와 adcioPlacement / adcioAnalytics가 동일한 adcioCore를 공유하고 있는지 판별하기 위함
- msw를 이용한 mockup 서버 구현
- 남은 테스트코드 작성
> ADCIO-1753) test: write adcio sdk test code

- .github/workflows/npm-publish.yml
Build
NONE
- publish 자동화가 안 되어 있습니다.
- 합니다.
- NPM_TOKEN 시크릿도 추가해두었습니다.
> NONE) build: add publish action

- src/__tests__/adcio.spec.ts
- src/__tests__/mock/handlers.ts
ADCIO-1811
- AdcioPlacement 모듈에 대한 테스트 코드가 존재하지 않았습니다.
- 모킹한 msw handler가 항상 resolve로 동작했습니다.
- AdcioPlacement 모듈에 대한 테스트 코드를 작성했습니다.
1. 존재하지 않는 placement id일 경우 에러가 발생하지 않음
2. 존재하는 placement id일 경우 404 에러가 발생
- msw handler를 수정해, api call이 실패하는 케이스일 경우 reject되게끔 변경했습니다.
테스트코드가 점차 많아지고 있어서, 각 모듈 별로 파일 분리를 할지 고민하고 있습니다.
- custom error 객체를 이용한 Placement 메서드(= createSuggestions) 에러 핸들링 구현
- 지면 비활성화 여부에 대한 에러 코드가 main에 반영되면, 그에 대한 테스트 코드 작성
> ADCIO-1811) test: test AdcioPlacement module

- src/__tests__/adcio.spec.ts
- src/adcio/adcio.ts
ADCIO-1890
analytics 모듈 메서드를 call했을 때 성공하는지 여부에 대한 테스트 코드를 작성했습니다.
<br />
참고) 실패하는 경우에 대한 테스트 코드를 작성하지 않은 이유
- 실패하는 경우에 대한 테스트 코드는 dto에 맞지 않은 인자를 전달했을 때에만 발생합니다.
- 이러한 경우는 타입스크립트에서 잡아주기 때문에, 일단 작성하지 않았습니다.
> test: test AdcioAnalytics module

- src/__tests__/adcio.spec.ts
- src/__tests__/mock/constants.ts
- src/__tests__/mock/handlers.ts
- src/__tests__/mock/suggestion.demo.ts
- src/api/controller/v1/api.ts
- src/lib/constants/error.ts
- src/lib/placement/placement.ts
ADCIO-1913
아래 2가지 경우에 대한 placement 모듈의 테스트 코드와 에러 핸들링을 구현했습니다.
- 1. placement id가 uuid가 아닌 경우
- 2. placement id가 지면 비활성화일 경우
[adcio placement 레포](https://github.com/corca-ai/adcio_placement)를 참고해 구현했습니다.
- Error 3가지 ([관련코드](https://github.com/corca-ai/adcio_placement/blob/main/lib/src/error.dart))
- ApiClient 연결 코드 ([에러 핸들링 관련 코드](https://github.com/corca-ai/adcio_placement/blob/main/lib/src/api_client.dart#L59-L79))
- test 코드
- ([when 조건 코드](https://github.com/corca-ai/adcio_placement/blob/main/test/adcio_placement_test.dart#L21-L63))
- ([expect 검증 코드](https://github.com/corca-ai/adcio_placement/blob/main/test/adcio_placement_test.dart#L104-L152))
> ADCIO-1913) test: test placement module Unit test for placement's deactivation error code

- .github/workflows/ci.yml
- src/__tests__/adcio.spec.ts
ADCIO-
- ci 파이프라인이 존재하지 않았습니다.
- github actions를 이용해 ci 파이프라인을 구축했습니다.
- main / develop 브랜치에 push 이벤트가 발생하거나 pull request가 올라오면 해당 ci 파이프라인이 돌게 됩니다.
> NONE) chore: implement ci workflows

- src/__tests__/mock/constants.ts
- src/adcio/adcio.interface.ts
- src/adcio/adcio.ts
- src/api/controller/v1/api.ts
- src/api/receiver/v1/api.ts
- src/lib/client-api/cafe24/index.ts
- src/lib/client-api/client-api.interface.ts
- src/lib/utils/dom.ts
> ADCIO-2386) fix: view event schema 

- src/adcio/adcio.ts
- src/lib/core/core.ts
- src/lib/placement/placement.ts
> ADCIO-2430) fix: customer id

- src/__tests__/mock/constants.ts
- src/adcio/adcio.interface.ts
- src/adcio/adcio.ts
- src/api/controller/v1/api.ts
- src/api/receiver/v1/api.ts
- src/lib/client-api/cafe24/index.ts
- src/lib/client-api/client-api.interface.ts
- src/lib/core/core.ts
- src/lib/placement/placement.ts
- src/lib/utils/dom.ts
> Release v0.1.7

- src/adcio/adcio.interface.ts
- src/adcio/adcio.ts
- src/api/controller/v1/api.ts
- src/lib/placement/index.ts
NONE
내일 "신규 안다르 테스트 스킨" 적용을 위해 필요한 작업입니다.
- displayPositions 타입이 추가되었습니다. (기존의 suggestionPosition 대체용)
- [참고 링크](https://api.adcio.ai/api#/Suggestion/SuggestionController_suggestProducts)
- 이번에 수정된 파일을 빌드하여 사용하면 다음과 같은 에러를 해소할 수 있습니다. (이미 안다르 테스트 스킨에는 해당 브랜치에서 빌드된 adcio js 및 adcio.js.map 파일을 사용하고 있습니다.)
**수정전**
**수정후 빌드 및 pc js 적용 확인 완료**
> NONE) fix: add suggestionProducts and update api diff

- src/adcio/adcio.ts
> NONE) fix: collect view if product or category

- src/adcio/adcio.interface.ts
- src/adcio/adcio.ts
- src/api/controller/v1/api.ts
- src/lib/placement/index.ts
- src/lib/placement/placement.interface.ts
- src/lib/placement/placement.ts
ADCIO-2908
- createSuggestion 함수를 사용합니다.
- createRecommendationProducts와 createRecommendationBanners로 분리합니다.
> ADCIO-2908) feat: add createRecommendationProducts and createRecommendationBanners

- mock/handlers.ts
- src/api/receiver/v1/api.ts
- src/lib/analytics/analytics.ts
ADCIO-3021
- `/performance` 하위 엔드포인트를 사용 중입니다.
- `/events` 하위 엔드포인트를 사용하도록 합니다.
> ADCIO-3021) fix: use only events controller

- demo/react/package.json
- demo/react/public/mockServiceWorker.js
- demo/react/vite.config.ts
- demo/react/yarn.lock
- package.json
- yarn.lock
ADCIO-
private가 true로 되어있어 npm 퍼블리쉬가 안 됩니다.
참고) private: true로 지정한 이유
- src를 demo/react에서 사용하기 위해 모노레포로 세팅하였기 때문입니다.
- private를 false로 수정했습니다.
- adcio.js를 내부 src 대신 퍼블리쉬된 npm을 이용하는 방식으로 수정했습니다.
> NONE) chore: remove private option

- src/lib/impression-observer/impression-observer.ts
NONE
- 50% 이상 노출된 즉시 impression이 수집됩니다.
- impression 측정 기준에 따라, 1초 이상 노출된 경우만 수집합니다.
> NONE) fix: impression timer

- packages/core/package.json
- packages/core/src/adcio.ts
NONE
- add-to-cart 에서 quantity가 누락되었습니다.
- 추가했습니다.
> NONE) fix: add-to-cart quantity

- packages/bootstrap/tsconfig.json
- packages/core/tsconfig.json
- packages/widget/tsconfig.json
ADCIO-
로컬에서 widget 빌드 결과물에 lib과 api 디팬던시가 포함되어 있으나,
`renderer export하는 부분에 module find 이슈가 발생`하는 것을 확인했습니다.
- tsconfig 파일을 확인해보니 "include": ["src/*.ts"]로 되어있어, src 디렉터리 바로 아래에 잇는 ts 파일만 포함되어 발생된 이슈입니다.
- include: [src]로 변경해 find module 이슈를 해결했습니다.
> NONE) fix: modify tscofing include option

- packages/agent/package.json
- packages/agent/src/app.tsx
- packages/agent/src/document.tsx
- packages/agent/src/index.ts
- packages/agent/tsconfig.json
- packages/agent/vite.config.ts
- packages/bootstrap/package.json
- pnpm-lock.yaml
ADCIO-4100
AA를 SDK로 배포하기 위해 빌드 설정을 해두어야 합니다.
vite를 이용해 AA에 SDK 빌드 세팅을 합니다.
해당 pr이 머지되면 AA를 npm으로 퍼블리쉬 하는 것이 좋아보여요.
npm으로 퍼블리쉬 하게 되면, 이제 rmp에 있던 AA 코드들을 다 삭제할 수 있어보여요.
> ADCIO-4100) chore: set aa build setting using vite

- .github/workflows/ci.yml
- demo/react/package.json
- demo/react/src/App.tsx
- demo/react/src/main.tsx
- packages/agent/package.json
- packages/agent/src/components/chatPage/ChatTop.tsx
- packages/agent/src/components/chatPage/chatTop/BottomSheet.tsx
- packages/agent/src/components/chatPage/chatTop/index.tsx
- packages/agent/src/components/layout/container/EntryContainer.tsx
- packages/agent/src/components/layout/container/PageContainer.tsx
- packages/agent/src/index.ts
- packages/agent/src/layout/container/EntryContainer.tsx
- packages/agent/src/layout/container/PageContainer.tsx
- packages/agent/src/pages/Start.tsx
- pnpm-lock.yaml
ADCIO-4113
AA 바텀 시트 틀을 만들었습니다.
> ADCIO-4113) feature: modify bottom sheet aa

- packages/agent/src/components/startPage/IntroductionText.tsx
- packages/agent/src/components/startPage/chatHistory/ChatHistoryContents.tsx
- packages/agent/src/components/startPage/chatHistory/chatList/Chat.tsx
- packages/agent/src/components/startPage/chatHistory/chatList/index.tsx
- packages/agent/src/components/startPage/chatHistory/index.tsx
- packages/agent/src/components/startPage/chatHistory/style.ts
- packages/agent/src/components/startPage/chatHistory/type.ts
- packages/agent/src/styles/scrollbar.ts
- packages/agent/vite.config.ts
- packages/api/vite.config.ts
- packages/bootstrap/package.json
- packages/bootstrap/src/bootstrap/index.ts
- packages/bootstrap/src/client-api/factory.ts
- packages/bootstrap/src/index.ts
- packages/bootstrap/src/run.ts
- packages/bootstrap/vite.config.run.ts
- packages/bootstrap/vite.config.ts
- packages/core/src/placement/placement.interface.ts
- packages/core/vite.config.ts
- packages/widget/vite.config.ts
ADCIO-
- iife 빌드 때 lib name에 대한 정리가 필요합니다.
- api, core, agent, widget
- adcio.api, adcio.core, ...
- bootstrap
- adcio
bootstrap 라이브러리는 올인원으로 모든 adcio 의존성이 포함될 예정이기 때문
> fix: lib name

- packages/bootstrap/src/client-api/cafe24/index.ts
ADCIO-4856
- 검색어 수집 시 출처 url을 함께 수집
> ADCIO-4856) fix: collect pathname for search log

- packages/bootstrap/src/bootstrap/placement.ts
- packages/widget/src/assets/templates/rosemom-grid/item-mo.html
- packages/widget/src/assets/templates/rosemom-grid/item.html
- packages/widget/src/assets/templates/rosemom-grid/list-mo.html
- packages/widget/src/assets/templates/rosemom-grid/list.html
- packages/widget/src/renderer/grid-renderer.ts
- packages/widget/src/renderer/index.ts
- packages/widget/src/renderer/rosemom-grid-renderer.ts
- packages/widget/src/renderer/rosemom-mo-grid-renderer.ts
> feat: rosemom
